# -*- coding: utf-8 -*-
"""Graphs_Thesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlQZR4h-XvwnMHepErBGp_y2mJKhX8se
"""

from google.colab import drive
drive.mount('/content/drive')

IMG_FOLDER_PATH = ''

from google.colab import files
import matplotlib.pyplot as plt
from PIL import Image
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
import numpy as np
from collections import defaultdict, Counter
import csv
import statistics as st

# ------------------------------------------------------------------
# FIGURE 1 — distribution of aesthetic ratings for each painting
# ------------------------------------------------------------------
import csv, statistics as st
from collections import defaultdict
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

SRC = "JASP_trials_long.csv"
OUT = "."


# Function to load and resize painting images
def get_painting_image(painting_id, size=(30, 30)):
    try:
        # match filename convention
        cleaned_painting_id = painting_id.replace(' ', '-')
        # Adding 'Copy of '
        img_name = f"Copy of {cleaned_painting_id}.png"
        img_path = os.path.join(IMG_FOLDER_PATH, img_name) # Use os.path.join for robust path construction
        img = Image.open(img_path)
        img.thumbnail(size, Image.LANCZOS)
        return OffsetImage(img, zoom=1)
    except FileNotFoundError:
        print(f"Warning: Image file not found for {painting_id} (expected: {img_path}). Skipping image.")
        return None
    except Exception as e:
        print(f"Error loading image for {painting_id}: {e}")
        return None

rows = [r for r in csv.DictReader(open(SRC))
        if r["exclude"] == "" and r["complete_ratings"] == "yes"
        and r["has_rating"] == "yes"]

by_painting = defaultdict(list)
quadrant = {}
for r in rows:
    by_painting[r["painting"]].append(float(r["rating"]))
    quadrant[r["painting"]] = (r["semantic_level"], r["perceptual_level"])

QCOL = {("high", "high"): "#1b4965", ("low", "high"): "#5fa8d3",
        ("high", "low"): "#c26b3e", ("low", "low"): "#e8b04b"}
QLAB = {("high", "high"): "High semantic, high perceptual",
        ("low", "high"): "Low semantic, high perceptual",
        ("high", "low"): "High semantic, low perceptual",
        ("low", "low"): "Low semantic, low perceptual"}

stats = []
for pid, vals in by_painting.items():
    vals = sorted(vals)
    n = len(vals)
    q1 = st.quantiles(vals, n=4)[0]
    q3 = st.quantiles(vals, n=4)[2]
    stats.append(dict(painting=pid, n=n, mean=st.mean(vals), median=st.median(vals),
                      q1=q1, q3=q3, lo=vals[0], hi=vals[-1],
                      quad=quadrant[pid]))


quadrant_order_map = {
    ("high", "high"): 0,
    ("low", "high"): 1,
    ("high", "low"): 2,
    ("low", "low"): 3
}

#order by quadrant
stats.sort(key=lambda d: (quadrant_order_map[d["quad"]], d["mean"]))

grand = st.mean(float(r["rating"]) for r in rows)

fig, ax = plt.subplots(figsize=(7.5, 8.4))
ax.axvline(grand, color="#999999", lw=1, ls="--", zorder=0)
ax.text(grand, len(stats) - 0.2, f"  grand mean {grand:.2f}",
        color="#666666", fontsize=8, va="bottom")

# Store painting IDs to be used as labels
painting_labels = [d["painting"] for d in stats]

for i, d in enumerate(stats):
    col = QCOL[d["quad"]]
    ax.plot([d["lo"], d["hi"]], [i, i], color=col, lw=0.9, alpha=0.45,
            solid_capstyle="round", zorder=1)
    ax.plot([d["q1"], d["q3"]], [i, i], color=col, lw=4.2, alpha=0.75,
            solid_capstyle="round", zorder=2)
    ax.plot([d["median"]], [i], marker="|", ms=11, mew=1.8,
            color="white", zorder=4)
    ax.plot([d["mean"]], [i], marker="o", ms=6.0, color=col,
            mec="white", mew=1.1, zorder=5)

    # Add painting ID text label
    ax.text(-2.3, i, d["painting"], ha="left", va="center", fontsize=8, color="#333333", zorder=6)

    # Align painting image
    img_offset = get_painting_image(d["painting"])
    if img_offset:
        ab = AnnotationBbox(img_offset, (-2.8, i),
                            xycoords='data',
                            boxcoords="offset points",
                            box_alignment=(1., 0.5),
                            frameon=False,
                            zorder=7)
        ax.add_artist(ab)

ax.set_yticks(range(len(stats)))
ax.set_yticklabels([])
ax.set_ylim(-0.8, len(stats) - 0.2)
ax.set_xlim(-3.0, 10.4)
ax.set_xticks(range(0, 11))
ax.set_xlabel("Aesthetic rating", fontsize=10)
ax.tick_params(axis="x", labelsize=9)
for side in ("top", "right", "left"):
    ax.spines[side].set_visible(False)
ax.grid(axis="x", color="#e6e6e6", lw=0.6, zorder=0)
ax.set_axisbelow(True)

handles = [Line2D([], [], color=QCOL[q], lw=4.2, alpha=0.75, label=QLAB[q])
           for q in [("high", "high"), ("low", "high"),
                     ("high", "low"), ("low", "low")]]
handles += [Line2D([], [], color="#444444", marker="o", ms=6, ls="",
                   mec="white", label="Mean"),
            Line2D([], [], color="#444444", marker="|", ms=11, mew=1.8, ls="",
                   label="Median")]
ax.legend(handles=handles, fontsize=8, frameon=False, ncol=2,
          loc="upper center", bbox_to_anchor=(0.5, -0.06))

fig.tight_layout()
for ext in ("png", "pdf"):
    fig.savefig(f"{OUT}/Figure_ratings_by_painting.{ext}", dpi=300,
                bbox_inches="tight")

print(f"{len(stats)} paintings, {len(rows)} ratings, grand mean {grand:.2f}")
print(f"painting means range {stats[0]['mean']:.2f} ({stats[0]['painting']}) "
      f"to {stats[-1]['mean']:.2f} ({stats[-1]['painting']})")
print(f"between-painting SD of means "
      f"{st.stdev(d['mean'] for d in stats):.2f}")

# ------------------------------------------------------------------
# FIGURE 2 — ablation table
# ------------------------------------------------------------------
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

OUT = "."

INK   = "#1b4965"
LIGHT = "#5fa8d3"
WARM  = "#c26b3e"
GREY  = "#9aa5ad"

# fixed effects, random effects, sample and outcome
FIXED  = ["Anchor\nvalue", "Anchor\nvalue²", "Condition", "Complexity\nquadrant",
          "Art\nengagement", "AI\nusage"]
RANDOM = ["Participant\nintercept", "Painting\nintercept", "Painting\nanchor slope"]
COLS   = FIXED + RANDOM

# name, [fixed flags], [random flags], cond levels, N, obs, verdict, verdict colour
ROWS = [
 ("H1  Does an anchor shift ratings?",
  [1,0,1,0,0,0], [1,1,1], 3, 84, 2268, "Supported", INK),
 ("H2  Does the attributed source matter?",
  [1,0,1,0,0,0], [1,1,1], 2, 84, 1512, "Not supported", GREY),
 ("H3  Does image complexity moderate it?",
  [1,0,1,1,0,0], [1,1,1], 3, 84, 2268, "Not supported", GREY),
 ("H4  Does art engagement moderate it?",
  [1,0,1,0,1,0], [1,1,1], 3, 82, 2214, "Not supported\n(source crossover)", WARM),
 ("Exploratory  AI usage as moderator",
  [1,0,1,0,0,1], [1,1,1], 3, 81, 2187, "No effect", GREY),
 ("Exploratory  Anchor extremity",
  [1,1,1,0,0,0], [1,1,1], 3, 84, 2268, "No effect", GREY),
]

n_rows, n_cols = len(ROWS), len(COLS)
SP = 1.55
X  = [j * SP for j in range(n_cols)]
RX = n_cols * SP
fig, ax = plt.subplots(figsize=(13.4, 4.9))

# ---- column band shading-----------------------------------
ax.axvspan(-0.75, X[len(FIXED)-1] + 0.75, color="#f2f6f8", zorder=0)
ax.axvspan(X[len(FIXED)-1] + 0.75, X[-1] + 0.75, color="#faf6f1", zorder=0)

for i in range(n_rows):
    y = n_rows - 1 - i
    if i % 2 == 0:
        ax.axhspan(y - 0.5, y + 0.5, color="#ffffff", alpha=0.55, zorder=1)

# ---- markers ---------------------------------------------------------------
for i, (name, fx, rn, lev, N, obs, verdict, vcol) in enumerate(ROWS):
    y = n_rows - 1 - i
    for j, on in enumerate(fx + rn):
        col = INK if j < len(FIXED) else LIGHT
        if on:
            ax.plot(X[j], y, "o", ms=13, color=col, zorder=3)
            if COLS[j] == "Condition":
                ax.text(X[j], y, str(lev), ha="center", va="center",
                        color="white", fontsize=8, fontweight="bold", zorder=4)
        else:
            ax.plot(X[j], y, "o", ms=13, mfc="none", mec="#d3dae0", mew=1.1, zorder=2)

    ax.text(-1.35, y, name, ha="right", va="center", fontsize=9.5, color="#222222")
    ax.text(RX + 0.25, y, f"{N}", ha="center", va="center",
            fontsize=9, color="#444444")
    ax.text(RX + 1.45, y, f"{obs:,}", ha="center", va="center",
            fontsize=9, color="#444444")
    ax.text(RX + 2.45, y, verdict, ha="left", va="center",
            fontsize=8.8, color=vcol,
            fontweight="bold" if vcol != GREY else "normal")

# ---- headers ---------------------------------------------------------------
for j, c in enumerate(COLS):
    ax.text(X[j], n_rows - 0.42, c, ha="center", va="bottom",
            fontsize=8.4, color="#333333", linespacing=1.3)

ax.text(X[len(FIXED)-1]/2, n_rows + 0.42, "F I X E D   E F F E C T S", ha="center",
        fontsize=8.5, color=INK, fontweight="bold")
ax.text((X[len(FIXED)]+X[-1])/2, n_rows + 0.42, "R A N D O M   E F F E C T S", ha="center",
        fontsize=8.5, color=LIGHT, fontweight="bold")
ax.text(RX + 0.25, n_rows - 0.42, "N", ha="center", va="bottom",
        fontsize=8.2, color="#333333")
ax.text(RX + 1.45, n_rows - 0.42, "Trials", ha="center", va="bottom",
        fontsize=8.2, color="#333333")
ax.text(RX + 2.45, n_rows - 0.42, "Outcome", ha="left", va="bottom",
        fontsize=8.2, color="#333333")

# ---- axes ------------------------------------------------------------------
ax.set_xlim(-6.4, RX + 4.9)
ax.set_ylim(-0.75, n_rows + 0.95)
ax.set_xticks([]); ax.set_yticks([])
for s in ax.spines.values(): s.set_visible(False)

fig.tight_layout()
for ext in ("png", "pdf"):
    fig.savefig(f"{OUT}/Figure_specifications.{ext}", dpi=300,
                bbox_inches="tight", facecolor="white")
print("wrote Figure_specifications.png / .pdf")
print(f"{n_rows} analyses, {n_cols} term columns")

for f in ("Figure_ratings_by_painting.png", "Figure_ratings_by_painting.pdf",
          "Figure_specifications.png", "Figure_specifications.pdf"):
    files.download(f)

# ------------------------------------------------------------------
# FIGURE 3 — Ratings by condition
# ------------------------------------------------------------------

INK, LIGHT, WARM, GOLD, GREY = "#1b4965", "#5fa8d3", "#c26b3e", "#e8b04b", "#9aa5ad"
CCOL = {"ai": INK, "human": WARM, "none": GREY}
CLAB = {"ai": "AI", "human": "Human", "none": "Control"}


SRC = "JASP_trials_long.csv"
trials = [r for r in csv.DictReader(open(SRC))
          if r["exclude"] == "" and r["complete_ratings"] == "yes"
          and r["has_rating"] == "yes"]


ratings_by_condition = defaultdict(list)
for r in trials:
    condition = r['condition']
    rating = int(float(r['rating']))
    ratings_by_condition[condition].append(rating)

# activate counter
rating_counts_by_condition = {cond: Counter(ratings) for cond, ratings in ratings_by_condition.items()}

fig, ax = plt.subplots(figsize=(12, 6))
rating_scale = np.arange(1, 11)
width = 0.25
sorted_conditions = sorted(CCOL.keys(), key=lambda k: CLAB[k])

# bar per condition
for i, cond_key in enumerate(sorted_conditions):
    counts = [rating_counts_by_condition[cond_key].get(r, 0) for r in rating_scale]
    x = rating_scale + (i - (len(sorted_conditions) - 1) / 2) * width

    ax.bar(x, counts, width, label=CLAB[cond_key], color=CCOL[cond_key], edgecolor='white', linewidth=0.5)

ax.set_xlabel("Rating (1-10)", fontsize=10)
ax.set_ylabel("Number of Ratings", fontsize=10)
ax.set_title("Distribution of Individual Ratings by Condition", loc='left', fontsize=12, pad=10)
ax.set_xticks(rating_scale)
ax.tick_params(axis="x", labelsize=9)
ax.tick_params(axis="y", labelsize=9)


ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_color("#cccccc")
ax.spines["bottom"].set_color("#cccccc")
ax.grid(axis="y", color="#e6e6e6", lw=0.6, zorder=0)
ax.set_axisbelow(True)

ax.legend(fontsize=8, frameon=False, loc="upper left")

fig.tight_layout()
for ext in ("png", "pdf"):
    fig.savefig(f"{OUT}/Figure_individual_ratings_by_condition.{ext}", dpi=300,
                bbox_inches="tight")

plt.show()

print(f"Generated Figure_individual_ratings_by_condition.png/pdf with distributions of individual ratings per condition.")