# -*- coding: utf-8 -*-
"""Stimuli Selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zWZpBz6lrlDjZPHF45FeoGKDjhLqStdv
"""

import pandas as pd
import numpy as np
from scipy.stats import entropy
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# --- 1. Load data ---
df = pd.read_csv("/content/Image_Annotations_QIP.csv")

# --- 2. Clean category labels ---
# Strip whitespace and lowercase to remove duplicate entries like 'furniture' / 'furniture '
# Map known typos to canonical names
CATEGORY_MAP = {
    "cloting":               "clothing",
    "insterior space":       "interior space",
    "achitectural element":  "architectural element",
    "architectural element ":"architectural element",
    "decoration":            "decorative object",
    "decor":                 "decorative object",
    "documents":             "document",
}

df["Category"] = (
    df["Category"]
    .str.strip()
    .str.lower()
    .replace(CATEGORY_MAP)
)

# --- 3. Clean and expand material labels ---

def extract_materials(cell):
    if pd.isna(cell):
        return []
    return [m.strip().lower() for m in str(cell).split(",") if m.strip()]

df["materials_list"] = df["Material"].apply(extract_materials)

# --- 4. Compute per-painting metrics ---
records = []

for painting_id, group in df.groupby("Picture ID"):

    # Object type count: number of distinct annotated object types
    object_type_count = len(group)

    # Total object count
    total_object_count = group["Count"].sum()

    # Category entropy: Shannon entropy over category labels
    # High = many different category types; Low = few repeated types
    cat_probs = group["Category"].value_counts(normalize=True)
    cat_entropy = entropy(cat_probs)

    # Unique categories
    unique_cats = group["Category"].nunique()

    # Material diversity: unique individual materials across all objects in the painting
    all_materials = [m for mlist in group["materials_list"] for m in mlist]
    unique_materials = len(set(all_materials))

    # Material entropy
    if all_materials:
        mat_probs = pd.Series(all_materials).value_counts(normalize=True)
        mat_entropy = entropy(mat_probs)
    else:
        mat_entropy = 0.0

    records.append({
        "painting":            painting_id,
        "object_type_count":   object_type_count,
        "total_object_count":  total_object_count,
        "unique_categories":   unique_cats,
        "category_entropy":    round(cat_entropy, 3),
        "unique_materials":    unique_materials,
        "material_entropy":    round(mat_entropy, 3),
    })

results = pd.DataFrame(records)

# --- 5. Composite complexity score ---
# Standardise object type count and category entropy, then sum equally
# (use object_type_count, not total_object_count, to avoid outlier inflation from e.g. 50 books)
results["obj_z"]     = (results["total_object_count"] - results["total_object_count"].mean()) / results["total_object_count"].std()
results["entropy_z"] = (results["category_entropy"]  - results["category_entropy"].mean())  / results["category_entropy"].std()
results["cat_z"]     = (results["object_type_count"] - results["object_type_count"].mean()) / results["object_type_count"].std()
results["composite"] = results["obj_z"] + results["entropy_z"] + results["cat_z"]

# --- 6. Assign complexity zones ---
def assign_zone(score):
    if score >  3.0: return "high"
    if score < -3.0: return "low"
    return "mid"

results["zone"] = results["composite"].apply(assign_zone)

# --- 7. Print summaries ---
print("=== Zone counts ===")
print(results["zone"].value_counts().to_string())

print("\n=== High complexity candidates ===")
high = results[results["zone"] == "high"].sort_values("composite", ascending=False)
print(high[["painting", "object_type_count", "unique_categories",
            "category_entropy", "unique_materials", "composite"]].to_string(index=False))

print("\n=== Low complexity candidates ===")
low = results[results["zone"] == "low"].sort_values("composite")
print(low[["painting", "object_type_count", "unique_categories",
           "category_entropy", "unique_materials", "composite"]].to_string(index=False))

# --- 8. Scatter plot ---
COLORS = {"high": "#7F77DD", "mid": "#B4B2A9", "low": "#1D9E75"}
SIZES  = {"high": 90,        "mid": 45,        "low": 90}
ALPHAS = {"high": 0.9,       "mid": 0.5,       "low": 0.9}

fig, ax = plt.subplots(figsize=(9, 6))

for zone in ["mid", "low", "high"]:
    sub = results[results["zone"] == zone]
    ax.scatter(
        sub["object_type_count"],
        sub["category_entropy"],
        c=COLORS[zone],
        s=SIZES[zone],
        alpha=ALPHAS[zone],
        edgecolors="white",
        linewidths=0.6,
        zorder={"mid": 1, "low": 2, "high": 2}[zone],
    )

# Annotate most extreme paintings in each zone
for _, row in high.head(5).iterrows():
    ax.annotate(row["painting"], xy=(row["object_type_count"], row["category_entropy"]),
                xytext=(4, 4), textcoords="offset points", fontsize=7, color="#3C3489")

for _, row in low.head(5).iterrows():
    ax.annotate(row["painting"], xy=(row["object_type_count"], row["category_entropy"]),
                xytext=(4, -10), textcoords="offset points", fontsize=7, color="#085041")

# Legend
n_mid = len(results[results["zone"] == "mid"])
patches = [
    mpatches.Patch(color="#7F77DD", label=f"High complexity — {len(high)} paintings (composite > 2.0)"),
    mpatches.Patch(color="#B4B2A9", label=f"Middle — {n_mid} paintings (excluded)"),
    mpatches.Patch(color="#1D9E75", label=f"Low complexity — {len(low)} paintings (composite < −2.0)"),
]
ax.legend(handles=patches, fontsize=9, framealpha=0.9, loc="upper left")

ax.set_xlabel("Object type count", fontsize=12)
ax.set_ylabel("Category entropy", fontsize=12)
ax.set_title("Painting complexity landscape", fontsize=13, fontweight="normal", pad=12)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.grid(alpha=0.15)

plt.tight_layout()
plt.savefig("complexity_landscape.png", dpi=150, bbox_inches="tight")
plt.show()
print("\nPlot saved to complexity_landscape.png")